name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: pt_BR
          SHOW_UPDATED_DATE: True
          SHOW_LINES_OF_CODE: True
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: True
          SYMBOL_VERSION: 2
          SHOW_EDITORS: false
          SHOW_OS: false
       
          
